spring.application.name=learn-spring
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/update tables on startup
spring.jpa.hibernate.ddl-auto=update

# Show generated SQL queries in the console
spring.jpa.show-sql=true

# 1. Set the default global fallback log level for everything in the application
logging.level.root=INFO

# 2. Grant maximum visibility to your own code package (shows your DEBUG and INFO logs)
logging.level.org.example.learnspring=DEBUG

# 3. Suppress noisy third-party frameworks to only show warnings or serious runtime errors
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.apache.tomcat=WARN

debug=true