spring.application.name=learn-spring
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/update tables on startup
spring.jpa.hibernate.ddl-auto=update

# Show generated SQL queries in the console
spring.jpa.show-sql=true

debug=true